# Generated by Django 5.2 on 2025-05-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
